#ifndef __RS485_SPEED_TEST_WIRE_H
#define __RS485_SPEED_TEST_WIRE_H

#define RS485_SPEED_PAYLOAD_MAGIC0              0x52U
#define RS485_SPEED_PAYLOAD_MAGIC1              0x35U
#define RS485_SPEED_PAYLOAD_VERSION             2U

#define RS485_SPEED_PAYLOAD_MAGIC0_OFFSET       0U
#define RS485_SPEED_PAYLOAD_MAGIC1_OFFSET       1U
#define RS485_SPEED_PAYLOAD_VERSION_OFFSET      2U
#define RS485_SPEED_PAYLOAD_COMMAND_OFFSET      3U
#define RS485_SPEED_PAYLOAD_INDEX_OFFSET        4U
#define RS485_SPEED_PAYLOAD_ROLE_OFFSET         5U
#define RS485_SPEED_PAYLOAD_FLAGS_OFFSET        6U
#define RS485_SPEED_PAYLOAD_BAUD_OFFSET         8U
#define RS485_SPEED_PAYLOAD_SEQUENCE_OFFSET     12U
#define RS485_SPEED_PAYLOAD_TICK_OFFSET         16U
#define RS485_SPEED_PAYLOAD_ACTUAL_BAUD_OFFSET  20U
#define RS485_SPEED_PAYLOAD_PATTERN_OFFSET      24U

typedef enum
{
    RS485_SPEED_COMMAND_DATA = 1U,
    RS485_SPEED_COMMAND_ECHO = 2U,
    RS485_SPEED_COMMAND_SET_BAUD = 3U,
    RS485_SPEED_COMMAND_ACK_BAUD = 4U,
    RS485_SPEED_COMMAND_SYNC = 5U,
    RS485_SPEED_COMMAND_SYNC_ACK = 6U
} RS485_SpeedCommand;

#endif
